### ISSUE TITLE
Student was not able to upload files after thesis end

### ISSUE THREAD

**Issue by MaximilianAnzinger** [ls1intum/thesis-track#347]
It's common that students upload files like the Feedbacklog & Presentation after the thesis end date. Currently this is not possible and students get prompted that they don't have the necessary rights.

**Comment by fabian-emilius** [comment]
Once submitted, the student cant change files anymore. The end date should not be relevant here and this only happens when the student marks the thesis as submitted. The advisor can still do changes to the files
