### ISSUE TITLE
[Meta Ticket] Instructor View

### ISSUE THREAD

**Issue by Mtze** [ls1intum/thesis-track#61]
- Application list and details side-by-side 
  - Instructors should be able to select one application which is then shown on the right hand side instead of a popup 
  - Keyboard Navigation (Arrows, HJKL, ...)
  - Show all PDFs in browser
- Thesis Dashboard 
  - Add new thesis project 
  - Show all running thesis in a calendar view, filter by instructor, type, ...
  - Show statistics (Running, completed, ...)
  
 
here is a rough mockup:
![image](https://github.com/ls1intum/thesis-track/assets/23171488/27042caa-f132-479c-a08c-33a3571ecde4)

**Comment by krusche** [comment]
There should still be a search / filter above the list of students (in the mockup this could be in the upper left corner)
