### ISSUE TITLE
Implement Student Information Editor Page

### ISSUE THREAD

**Issue by fabian-emilius** [ls1intum/thesis-track#69]
On this page students should fill out information about themself
* This page is only accessible when logged in as student
* This page is required before applying for specific topics or suggesting a topic
* This Data needs to be uploaded
  * First Name
  * Last Name
  * Gender 
  * Nationality 
  * Study Degree
  * Study Program
  * Current Semester
  * File Uploads
    * CV
    * Grade Report
    * Bachelor Report
  * Text Fields
      * About Yourself
      * Previous Projects
      * Special Skills (Programming languages)
* Student should accept terms of the chair
* This data is fetched from tum login 
    * student id
    * matriculation number
    * email
* You should be able to save the data even if you haven’t filled out everything
* On the page it should show the completion rate (5/10 Information added)

Design reference: https://www.figma.com/design/MbWhKoeVb4qzXPesyj2Ivz/Thesis-Track?node-id=4-21&t=jT0CsyCyiC1k0QDC-0

**Comment by Mtze** [comment]
We need gender and nationality
