### ISSUE TITLE
Implement reusable hook for authentication

### ISSUE THREAD

**Issue by fabian-emilius** [ls1intum/thesis-track#84]
Implement reusable hook to check user groups and permissions

**Comment by Mtze** [comment]
Please make sure to have these roles in keycloak / in the JWT only. That would be super important to me

**Comment by fabian-emilius** [comment]
I can put these roles in keycloak but not sure if it makes some things harder as my idea of the permissions were to make them topic / thesis based. 
Example:
- If you create a new topic which students can apply to, the creator can define Reviewers that will have permissions to review the applications for that topic
- If you start a new thesis, each thesis can have students, instructors and graders and only the accounts added to this list can see / edit that specific thesis

so in my idea there is not really a global role (apart from maybe a global admin) but only roles for specific thesis / topics. Does that make sense? Generally I will use keycloak for all global permission stuff
